-- Migración: Creación de tablas de infraestructura centralizadas (Auditoría, Métricas y Colas)
-- Proyecto: Core

-- Tipos ENUM para estados de cola
DO $$ BEGIN
    CREATE TYPE public.client_email_queue_status AS ENUM ('PENDING', 'SENT', 'FAILED', 'PROCESSING');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.client_whatsapp_queue_status AS ENUM ('PENDING', 'SENT', 'FAILED', 'PROCESSING');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 1. Tabla: audit_logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    tenant_id uuid NOT NULL,
    platform_id uuid NOT NULL,
    branch_id uuid,
    action text NOT NULL,
    entity_type text,
    entity_id uuid,
    object_type text,
    object_id uuid,
    old_value jsonb,
    new_value jsonb,
    metadata jsonb,
    ip_address inet,
    user_agent text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
    CONSTRAINT audit_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
    CONSTRAINT audit_logs_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id)
);

-- 2. Tabla: api_request_metrics
CREATE TABLE IF NOT EXISTS public.api_request_metrics (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid NOT NULL,
    platform_id uuid NOT NULL,
    path text,
    method text,
    status_code integer,
    response_time_ms integer,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT api_request_metrics_pkey PRIMARY KEY (id),
    CONSTRAINT api_request_metrics_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
    CONSTRAINT api_request_metrics_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id)
);

-- 3. Tabla: client_email_queue
CREATE TABLE IF NOT EXISTS public.client_email_queue (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    platform_id uuid,
    recipient_client_id uuid,
    recipient_email text NOT NULL,
    template_type text NOT NULL,
    template_data jsonb,
    status public.client_email_queue_status NOT NULL DEFAULT 'PENDING'::client_email_queue_status,
    attempts integer NOT NULL DEFAULT 0,
    last_attempt_at timestamp with time zone,
    error_message text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT client_email_queue_pkey PRIMARY KEY (id),
    CONSTRAINT client_email_queue_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
    CONSTRAINT client_email_queue_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id)
);

-- 4. Tabla: client_whatsapp_queue
CREATE TABLE IF NOT EXISTS public.client_whatsapp_queue (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    platform_id uuid,
    recipient_client_id uuid,
    recipient_phone_number text NOT NULL,
    template_name text NOT NULL,
    template_params jsonb,
    status public.client_whatsapp_queue_status NOT NULL DEFAULT 'PENDING'::client_whatsapp_queue_status,
    attempts integer NOT NULL DEFAULT 0,
    last_attempt_at timestamp with time zone,
    error_message text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT client_whatsapp_queue_pkey PRIMARY KEY (id),
    CONSTRAINT client_whatsapp_queue_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
    CONSTRAINT client_whatsapp_queue_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id)
);

-- Índices básicos para rendimiento
CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant ON public.audit_logs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_api_metrics_created_at ON public.api_request_metrics(created_at);
CREATE INDEX IF NOT EXISTS idx_email_queue_status ON public.client_email_queue(status);
CREATE INDEX IF NOT EXISTS idx_whatsapp_queue_status ON public.client_whatsapp_queue(status);
