-- Migration to create a temporary table for debugging RPC functions

BEGIN;

CREATE TABLE public.debug_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  message TEXT,
  details JSONB
);

COMMIT;
