ALTER TABLE public.absence_types ADD CONSTRAINT absence_types_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.attention_products ADD CONSTRAINT attention_products_attention_id_fkey PRIMARY KEY (platform_id, attention_id, tenant_id);
ALTER TABLE public.attention_services ADD CONSTRAINT attention_services_attention_id_fkey PRIMARY KEY (attention_id, platform_id, tenant_id);
ALTER TABLE public.attentions ADD CONSTRAINT attentions_tenant_id_fkey PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.branch_combo_item_prices ADD CONSTRAINT branch_combo_item_prices_branch_id_fkey PRIMARY KEY (tenant_id, branch_id, platform_id);
ALTER TABLE public.branch_combo_item_prices ADD CONSTRAINT branch_combo_item_prices_combo_id_fkey PRIMARY KEY (combo_id, platform_id, tenant_id);
ALTER TABLE public.branch_combo_item_prices ADD CONSTRAINT branch_combo_item_prices_product_id_fkey PRIMARY KEY (tenant_id, product_id, platform_id);
ALTER TABLE public.branch_combo_item_prices ADD CONSTRAINT branch_combo_item_prices_service_id_fkey PRIMARY KEY (platform_id, service_id, tenant_id);
ALTER TABLE public.branch_combos ADD CONSTRAINT branch_combos_branch_id_fkey PRIMARY KEY (platform_id, tenant_id, branch_id);
ALTER TABLE public.branch_combos ADD CONSTRAINT branch_combos_combo_id_fkey PRIMARY KEY (combo_id, tenant_id, platform_id);
ALTER TABLE public.branch_photos ADD CONSTRAINT fk_branch_photos_branch PRIMARY KEY (tenant_id, platform_id, branch_id);
ALTER TABLE public.branch_photos ADD CONSTRAINT fk_branch_photos_tenant PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.branch_products ADD CONSTRAINT branch_products_branch_id_fkey PRIMARY KEY (branch_id, platform_id, tenant_id);
ALTER TABLE public.branch_products ADD CONSTRAINT branch_products_product_id_fkey PRIMARY KEY (product_id, tenant_id, platform_id);
ALTER TABLE public.branch_services ADD CONSTRAINT branch_services_branch_id_fkey PRIMARY KEY (branch_id, tenant_id, platform_id);
ALTER TABLE public.branch_services ADD CONSTRAINT branch_services_service_id_fkey PRIMARY KEY (service_id, tenant_id, platform_id);
ALTER TABLE public.branch_social_networks ADD CONSTRAINT branch_social_networks_branch_id_fkey PRIMARY KEY (platform_id, tenant_id, branch_id);
ALTER TABLE public.branches ADD CONSTRAINT fk_branches_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.chatter_attachments ADD CONSTRAINT chatter_attachments_chatter_comment_id_fkey PRIMARY KEY (chatter_comment_id, platform_id, tenant_id);
ALTER TABLE public.chatter_attachments ADD CONSTRAINT chatter_attachments_user_id_fkey PRIMARY KEY (user_id);
ALTER TABLE public.chatter_comments ADD CONSTRAINT chatter_comments_tenant_id_fkey PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.chatter_comments ADD CONSTRAINT chatter_comments_user_id_fkey PRIMARY KEY (user_id);
ALTER TABLE public.client_addresses ADD CONSTRAINT client_addresses_client_id_fkey PRIMARY KEY (client_id, platform_id, tenant_id);
ALTER TABLE public.client_addresses ADD CONSTRAINT client_addresses_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.client_branches ADD CONSTRAINT fk_client_branches_branch PRIMARY KEY (branch_id, platform_id, tenant_id);
ALTER TABLE public.client_branches ADD CONSTRAINT fk_client_branches_client PRIMARY KEY (tenant_id, client_id, platform_id);
ALTER TABLE public.client_branches ADD CONSTRAINT fk_client_branches_tenant PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.client_consent_records ADD CONSTRAINT client_consent_records_client_id_fkey PRIMARY KEY (platform_id, tenant_id, client_id);
ALTER TABLE public.client_consent_records ADD CONSTRAINT fk_client_consent_records_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.client_contacts ADD CONSTRAINT client_contacts_client_id_fkey PRIMARY KEY (client_id, tenant_id, platform_id);
ALTER TABLE public.client_contacts ADD CONSTRAINT client_contacts_contact_type_id_fkey PRIMARY KEY (tenant_id, platform_id, contact_type_id);
ALTER TABLE public.client_contacts ADD CONSTRAINT client_contacts_tenant_id_fkey PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.client_document_instances ADD CONSTRAINT client_document_instances_client_id_fkey PRIMARY KEY (client_id, platform_id, tenant_id);
ALTER TABLE public.client_document_instances ADD CONSTRAINT client_document_instances_template_id_fkey PRIMARY KEY (platform_id, template_id, tenant_id);
ALTER TABLE public.client_document_instances ADD CONSTRAINT fk_client_document_instances_attention PRIMARY KEY (attention_id, tenant_id, platform_id);
ALTER TABLE public.client_document_instances ADD CONSTRAINT fk_client_document_instances_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.client_document_templates ADD CONSTRAINT client_document_templates_tenant_id_fkey PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.client_treatment_session_items ADD CONSTRAINT client_treatment_session_items_client_treatment_session_id_fkey PRIMARY KEY (tenant_id, client_treatment_session_id, platform_id);
ALTER TABLE public.client_treatment_session_items ADD CONSTRAINT client_treatment_session_items_product_id_fkey PRIMARY KEY (tenant_id, platform_id, product_id);
ALTER TABLE public.client_treatment_session_items ADD CONSTRAINT client_treatment_session_items_service_id_fkey PRIMARY KEY (platform_id, service_id, tenant_id);
ALTER TABLE public.client_treatment_sessions ADD CONSTRAINT client_treatment_sessions_client_treatment_id_fkey PRIMARY KEY (platform_id, client_treatment_id, tenant_id);
ALTER TABLE public.client_treatment_sessions ADD CONSTRAINT client_treatment_sessions_prototype_session_id_fkey PRIMARY KEY (platform_id, tenant_id, prototype_session_id);
ALTER TABLE public.client_treatment_sessions ADD CONSTRAINT fk_client_treatment_sessions_attention PRIMARY KEY (platform_id, tenant_id, attention_id);
ALTER TABLE public.client_treatments ADD CONSTRAINT client_treatments_client_id_fkey PRIMARY KEY (tenant_id, client_id, platform_id);
ALTER TABLE public.client_treatments ADD CONSTRAINT client_treatments_prototype_id_fkey PRIMARY KEY (prototype_id, tenant_id, platform_id);
ALTER TABLE public.clients ADD CONSTRAINT fk_clients_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.combo_images ADD CONSTRAINT fk_combo_images_combo PRIMARY KEY (platform_id, combo_id, tenant_id);
ALTER TABLE public.combo_images ADD CONSTRAINT fk_combo_images_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.combo_items ADD CONSTRAINT combo_items_combo_id_fkey PRIMARY KEY (platform_id, tenant_id, combo_id);
ALTER TABLE public.combo_items ADD CONSTRAINT combo_items_product_id_fkey PRIMARY KEY (platform_id, product_id, tenant_id);
ALTER TABLE public.combo_items ADD CONSTRAINT combo_items_service_id_fkey PRIMARY KEY (platform_id, service_id, tenant_id);
ALTER TABLE public.consent_signatures ADD CONSTRAINT fk_consent_signatures_branch PRIMARY KEY (branch_id, tenant_id, platform_id);
ALTER TABLE public.consent_signatures ADD CONSTRAINT fk_consent_signatures_signed_consent PRIMARY KEY (signed_consent_id, tenant_id, platform_id);
ALTER TABLE public.consent_signatures ADD CONSTRAINT fk_consent_signatures_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.consent_signatures ADD CONSTRAINT fk_consent_signatures_user PRIMARY KEY (user_id);
ALTER TABLE public.equipment ADD CONSTRAINT equipment_brand_id_fkey PRIMARY KEY (tenant_id, platform_id, brand_id);
ALTER TABLE public.equipment ADD CONSTRAINT equipment_tenant_id_fkey PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.equipment ADD CONSTRAINT equipment_type_id_fkey PRIMARY KEY (platform_id, type_id, tenant_id);
ALTER TABLE public.equipment_assignments ADD CONSTRAINT equipment_assignments_branch_id_fkey PRIMARY KEY (tenant_id, platform_id, branch_id);
ALTER TABLE public.equipment_assignments ADD CONSTRAINT equipment_assignments_equipment_id_fkey PRIMARY KEY (tenant_id, platform_id, equipment_id);
ALTER TABLE public.equipment_assignments ADD CONSTRAINT equipment_assignments_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.equipment_assignments ADD CONSTRAINT equipment_assignments_user_id_fkey PRIMARY KEY (user_id);
ALTER TABLE public.equipment_brands ADD CONSTRAINT equipment_brands_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.equipment_maintenance_history ADD CONSTRAINT equipment_maintenance_history_equipment_id_fkey PRIMARY KEY (platform_id, tenant_id, equipment_id);
ALTER TABLE public.equipment_maintenance_history ADD CONSTRAINT equipment_maintenance_history_tenant_id_fkey PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.equipment_types ADD CONSTRAINT equipment_types_tenant_id_fkey PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.expense_provider_addresses ADD CONSTRAINT fk_expense_provider_addresses_provider PRIMARY KEY (expense_provider_id, tenant_id, platform_id);
ALTER TABLE public.expense_provider_addresses ADD CONSTRAINT fk_expense_provider_addresses_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.expense_provider_contacts ADD CONSTRAINT fk_expense_provider_contacts_contact_type PRIMARY KEY (contact_type_id, tenant_id, platform_id);
ALTER TABLE public.expense_provider_contacts ADD CONSTRAINT fk_expense_provider_contacts_provider PRIMARY KEY (platform_id, tenant_id, expense_provider_id);
ALTER TABLE public.expense_provider_contacts ADD CONSTRAINT fk_expense_provider_contacts_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.expense_providers ADD CONSTRAINT fk_expense_providers_document_type PRIMARY KEY (document_type_id, platform_id, tenant_id);
ALTER TABLE public.expense_providers ADD CONSTRAINT fk_expense_providers_tenant PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.expenses ADD CONSTRAINT fk_expenses_branch PRIMARY KEY (tenant_id, branch_id, platform_id);
ALTER TABLE public.expenses ADD CONSTRAINT fk_expenses_provider PRIMARY KEY (expense_provider_id, platform_id, tenant_id);
ALTER TABLE public.expenses ADD CONSTRAINT fk_expenses_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.informed_consent_templates ADD CONSTRAINT fk_informed_consent_templates_tenant PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.invoice_items ADD CONSTRAINT invoice_items_invoice_id_fkey PRIMARY KEY (platform_id, invoice_id, tenant_id);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.media_playlists ADD CONSTRAINT media_playlists_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.playlist_items ADD CONSTRAINT playlist_items_playlist_id_fkey PRIMARY KEY (platform_id, tenant_id, playlist_id);
ALTER TABLE public.product_category_assignments ADD CONSTRAINT product_category_assignments_category_id_fkey PRIMARY KEY (category_id, platform_id, tenant_id);
ALTER TABLE public.product_category_assignments ADD CONSTRAINT product_category_assignments_product_id_fkey PRIMARY KEY (product_id, platform_id, tenant_id);
ALTER TABLE public.product_images ADD CONSTRAINT product_images_product_id_fkey PRIMARY KEY (platform_id, tenant_id, product_id);
ALTER TABLE public.product_images ADD CONSTRAINT product_images_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.product_transfer_items ADD CONSTRAINT product_transfer_items_product_id_fkey PRIMARY KEY (platform_id, tenant_id, product_id);
ALTER TABLE public.product_transfer_items ADD CONSTRAINT product_transfer_items_transfer_id_fkey PRIMARY KEY (tenant_id, transfer_id, platform_id);
ALTER TABLE public.product_transfer_reception_items ADD CONSTRAINT product_transfer_reception_items_product_id_fkey PRIMARY KEY (tenant_id, platform_id, product_id);
ALTER TABLE public.product_transfer_reception_items ADD CONSTRAINT product_transfer_reception_items_reception_id_fkey PRIMARY KEY (reception_id, tenant_id, platform_id);
ALTER TABLE public.product_transfer_reception_items ADD CONSTRAINT product_transfer_reception_items_transfer_item_id_fkey PRIMARY KEY (platform_id, tenant_id, transfer_item_id);
ALTER TABLE public.product_transfer_receptions ADD CONSTRAINT product_transfer_receptions_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.product_transfer_receptions ADD CONSTRAINT product_transfer_receptions_transfer_id_fkey PRIMARY KEY (transfer_id, platform_id, tenant_id);
ALTER TABLE public.product_transfers ADD CONSTRAINT product_transfers_from_branch_id_fkey PRIMARY KEY (platform_id, tenant_id, origin_branch_id);
ALTER TABLE public.product_transfers ADD CONSTRAINT product_transfers_requesting_branch_id_fkey PRIMARY KEY (requesting_branch_id, tenant_id, platform_id);
ALTER TABLE public.product_transfers ADD CONSTRAINT product_transfers_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.product_transfers ADD CONSTRAINT product_transfers_to_branch_id_fkey PRIMARY KEY (platform_id, tenant_id, destination_branch_id);
ALTER TABLE public.products ADD CONSTRAINT fk_products_tenant PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.purchase_items ADD CONSTRAINT purchase_items_purchase_id_fkey PRIMARY KEY (platform_id, tenant_id, purchase_id);
ALTER TABLE public.purchases ADD CONSTRAINT purchases_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.recurring_expenses ADD CONSTRAINT fk_recurring_expenses_branch PRIMARY KEY (tenant_id, platform_id, branch_id);
ALTER TABLE public.recurring_expenses ADD CONSTRAINT fk_recurring_expenses_provider PRIMARY KEY (tenant_id, platform_id, expense_provider_id);
ALTER TABLE public.recurring_expenses ADD CONSTRAINT fk_recurring_expenses_tenant PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.sales ADD CONSTRAINT sales_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.sales_items ADD CONSTRAINT sales_items_sale_id_fkey PRIMARY KEY (sale_id, platform_id, tenant_id);
ALTER TABLE public.service_images ADD CONSTRAINT fk_service_images_service PRIMARY KEY (tenant_id, service_id, platform_id);
ALTER TABLE public.service_images ADD CONSTRAINT fk_service_images_tenant PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.services ADD CONSTRAINT fk_services_tenant PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.signed_consents ADD CONSTRAINT fk_signed_consents_attention PRIMARY KEY (platform_id, tenant_id, attention_id);
ALTER TABLE public.signed_consents ADD CONSTRAINT fk_signed_consents_attention_service PRIMARY KEY (tenant_id, platform_id, attention_service_id, attention_id);
ALTER TABLE public.signed_consents ADD CONSTRAINT fk_signed_consents_client PRIMARY KEY (tenant_id, platform_id, client_id);
ALTER TABLE public.signed_consents ADD CONSTRAINT fk_signed_consents_professional PRIMARY KEY (professional_id);
ALTER TABLE public.signed_consents ADD CONSTRAINT fk_signed_consents_template PRIMARY KEY (platform_id, tenant_id, template_id);
ALTER TABLE public.signed_consents ADD CONSTRAINT fk_signed_consents_tenant PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.suppliers ADD CONSTRAINT fk_suppliers_tenant PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.tenant_social_networks ADD CONSTRAINT tenant_social_networks_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.treatment_categories ADD CONSTRAINT treatment_categories_tenant_id_fkey PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.treatment_category_assignments ADD CONSTRAINT treatment_category_assignments_category_id_fkey PRIMARY KEY (category_id, platform_id, tenant_id);
ALTER TABLE public.treatment_category_assignments ADD CONSTRAINT treatment_category_assignments_treatment_id_fkey PRIMARY KEY (platform_id, treatment_id, tenant_id);
ALTER TABLE public.treatment_images ADD CONSTRAINT treatment_images_treatment_id_fkey PRIMARY KEY (platform_id, tenant_id, treatment_id);
ALTER TABLE public.treatment_session_items ADD CONSTRAINT treatment_session_items_product_id_fkey PRIMARY KEY (product_id, tenant_id, platform_id);
ALTER TABLE public.treatment_session_items ADD CONSTRAINT treatment_session_items_service_id_fkey PRIMARY KEY (platform_id, service_id, tenant_id);
ALTER TABLE public.treatment_session_items ADD CONSTRAINT treatment_session_items_session_id_fkey PRIMARY KEY (platform_id, tenant_id, session_id);
ALTER TABLE public.treatment_sessions ADD CONSTRAINT treatment_sessions_treatment_id_fkey PRIMARY KEY (platform_id, tenant_id, treatment_id);
ALTER TABLE public.treatments ADD CONSTRAINT treatments_tenant_id_fkey PRIMARY KEY (tenant_id, platform_id);
ALTER TABLE public.tv_displays ADD CONSTRAINT tv_displays_branch_id_fkey PRIMARY KEY (branch_id, platform_id, tenant_id);
ALTER TABLE public.tv_displays ADD CONSTRAINT tv_displays_tenant_id_fkey PRIMARY KEY (platform_id, tenant_id);
ALTER TABLE public.user_assignments ADD CONSTRAINT user_assignments_branch_id_fkey PRIMARY KEY (platform_id, tenant_id, branch_id);
ALTER TABLE public.user_assignments ADD CONSTRAINT user_assignments_role_id_fkey PRIMARY KEY (role_id);
ALTER TABLE public.user_assignments ADD CONSTRAINT user_assignments_user_id_fkey PRIMARY KEY (user_id);